services:
  - type: web
    name: reddit-sentiment-api
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r api_requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        sync: false
